sudo: required
dist: trusty

addons:
  apt:
    packages:
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-latex-recommended
      - texlive-lang-german
      - texlive-science
      - latex-xcolor
script:
  - make script
