name: build
on:
  push: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug - List files (after checkout)
        run: ls -la

      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            apk add g++
            apk add zip
            make script zip

      - name: Change file ownership to runner
        run: |
            sudo chown runner:docker vorkurs.pdf
            sudo chown runner:docker vorkurs.zip

      - name: Debug - List files (after build)
        run: ls -la

      - name: Debug - Verify vorkurs.pdf exists and is not empty
        run: |
          if [ -f "vorkurs.pdf" ] && [ -s "vorkurs.pdf" ]; then
            echo "vorkurs.pdf exists and is not empty."
          else
            echo "ERROR: vorkurs.pdf does not exist or is empty!"
            exit 1
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: vorkurs.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vorkurs.pdf
            vorkurs.zip
