name: build
on: 
  push: {}
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with: 
          scheme: full
          run: |
            apk add make
            apk add g++
            apk add zip
            make script zip
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: vorkurs.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vorkurs.pdf
            vorkurs.zip
      
