name: Build and Run Tests

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full # Consider changing to 'basic' or 'medium' if possible
          run: |
            apk add make
            apk add g++
            apk add zip
            make script zip
      - uses: actions/upload-artifact@v4
        with:
          name: PDF_Test
          path: vorkurs.pdf

  check-links:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download compiled PDF
        uses: actions/download-artifact@v4
        with:
          name: PDF_Test
          path: .

      - name: Install pdfgrep
        run: sudo apt-get update && sudo apt-get install -y pdfgrep

      - name: Install required python package
        run: pip install urllib3

      - name: Run Link Checker
        run: python .github/workflows/test_scripts/check_links.py

  check-compilability:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run compilability checker
        run: python .github/workflows/test_scripts/check_compilability.py

  latexindent-check:
    runs-on: xu-cheng/texlive-action@v2
    steps:
      - uses: actions/checkout@v4

      - name: Install latexindent dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y perl libyaml-tiny-perl libfile-homedir-perl libfile-find-rule-perl
          sudo cpan -i Unicode::GCString

      - name: Check formatting of all .tex files
        run: |
          find . -name "*.tex" | while read file; do
            latexindent "$file" > "$file.formatted"
            if ! diff -q "$file" "$file.formatted" > /dev/null; then
              echo "::error file=$file::File is not properly formatted. Run 'make format' locally."
              exit 1
            fi
            rm "$file.formatted"
          done
