name: Run Tests

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            apk add g++
            apk add zip
            make script zip
      - uses: actions/upload-artifact@v4
        with:
          name: PDF_Test
          path: vorkurs.pdf

  check-links:
    runs-on: ubuntu-latest
    needs: build  # This is crucial: check-links runs AFTER build
    steps:
      - name: Checkout code  # Not strictly necessary, but good practice
        uses: actions/checkout@v4

      - name: Download compiled PDF
        uses: actions/download-artifact@v4
        with:
          name: PDF_Test
          path: .

      - name: Install pdfgrep
        run: sudo apt-get update && sudo apt-get install -y pdfgrep

      - name: Extract and Check URLs
        run: |
          # 1. Extract URLs using pdfgrep
          urls=$(pdfgrep -o -P 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' vorkurs.pdf | sort -u)

          # 2. Check each URL
          error_count=0
          for url in $urls; do
            echo "Checking URL: $url"
            if ! curl -Isf --fail-early --connect-timeout 10 "$url" > /dev/null; then
              echo "ERROR: Failed to access or invalid certificate: $url"
              error_count=$((error_count + 1))
            fi

            # Explicitly check for HTTPS
            if [[ ! "$url" =~ ^https:// ]]; then
              echo "ERROR: URL is not HTTPS: $url"
              error_count=$((error_count + 1))
            fi
          done

          # 3. Fail the workflow if any errors were found
          if [ "$error_count" -gt 0 ]; then
            echo "::error::Found $error_count broken or insecure links!"
            exit 1
          fi
        shell: bash
